version: "3"
services:
  web:
    container_name: mc-webpage
    image: nginx:latest
    ports:
      - "25555:80"
    volumes:
      - "./web:/usr/share/nginx/html"
    restart: always

networks:
  proxy:
    name: nginx_proxy_manager_default
    external: true
